---
title: "p8105_hw6_hw2850"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

###Problem 2
```{r}
#read data
homicide = read_csv("data/homicide-data.csv") %>% 
  janitor::clean_names()
```

```{r}
homicide_tidy = homicide %>% 
  mutate(
    city_state = str_c(city, ", " ,state), #create city_state variable
    disposition = if_else(disposition %in% "Closed by arrest", 1, 0)
    ) %>% #make disposition a binary variable
  filter(!city_state %in% c("Dallas, TX", "Phoenix, AZ", "Kansas City, MO", "Tulsa, AL"),
         victim_race %in% c("White", "Black")) %>% #Only select white & black
  mutate(victim_age = as.numeric(victim_age), #make age numeric
         victim_race = fct_relevel(victim_race, "White"),
         disposition = as.numeric(disposition)) %>% 
  select(!c(city, state))
```

```{r}
Baltimore = homicide_tidy %>% 
  filter(city_state == "Baltimore, MD") #get Baltimore data

Baltimore_fit = Baltimore %>% 
  glm(disposition ~ victim_age + victim_sex + victim_race, data = ., family = binomial()) #run glm

Baltimore_results = Baltimore_fit %>% 
  broom::tidy(conf.int = T) %>% 
  mutate(OR = exp(estimate)) %>%
  select(term, log_OR = estimate, OR, p.value, conf.low, conf.high) 
```

```{r}
homicide_nest = homicide_tidy %>% 
  select(city_state, victim_race, victim_age, victim_sex, disposition) %>%
  nest(data = -city_state) %>% #nest data and run glm on each city
  mutate(models = map(data, ~glm(disposition ~ victim_age + victim_sex + victim_race, data = .x, family = binomial())),
         results = map(models, ~broom::tidy(x = .x, conf.int = T))) %>% 
  select(-data, -models) %>% 
  unnest(results) %>% 
  filter(term %in% "victim_sexMale") %>% #only need sex coefficients
  mutate(OR = exp(estimate),
         conf.low = exp(conf.low),
         conf.high = exp(conf.high))
```

```{r}
homicide_plot = homicide_nest %>% 
  ggplot(aes(x = OR, y = reorder(city_state, OR)))+
  geom_point()+
  geom_errorbar(aes(xmin = conf.low, xmax = conf.high))+
  labs(
    title = "Adjusted OR and CI for Solving Homicides Comparing Victims Gender",
    x = "Odds Ratio",
    y = "City_State"
  )

homicide_plot
```


###Problem 3
```{r}
birthwt = read_csv("data/birthweight.csv") %>% 
  janitor::clean_names()
```
Interested in investigating the relationship between mother's pre-pregnancy weight (ppwt) and baby's birth weight.

```{r}
birthwt %>% 
  ggplot(aes(x = ppwt, y = bwt)) +
  geom_point(alpha = .5) #plot the trend between ppwt and bwt
```
From the graph, there could be a linear relationship between ppwt and bwt. Therefore, lets fit a simple linear regression model.

```{r}
#fit a SLR model
linear_mod = lm(bwt ~ ppwt, data = birthwt)
linear_mod %>% 
  broom::tidy()
```

```{r}
modelr::add_predictions(birthwt, linear_mod)
modelr::add_residuals(birthwt, linear_mod)
birthwt

birthwt_plot = birthwt %>% 
  modelr::add_residuals(linear_mod) %>% #add residuals
  modelr::add_predictions(linear_mod) %>% #add predictions
  ggplot(aes(x = pred, y = resid))+
  geom_point()+
  geom_smooth(se = F, method = "lm")

birthwt_plot
```

```{r}
#run MLR model with length at birth and gestational age
mlr_mod = lm(bwt ~ blength + gaweeks, data = birthwt) 
summary(mlr_mod)

#run MLR model with head circumference, length, sex and their interactions
interaction_mod = lm(bwt ~ bhead*blength*babysex, data = birthwt)
summary(interaction_mod)
```

```{r}
#load packages
library(modelr)
library(mgcv)

#plot three models
birthwt %>% 
  gather_predictions(linear_mod, mlr_mod, interaction_mod) %>% 
  mutate(model = fct_inorder(model)) %>% 
  ggplot(aes(x = ppwt, y = bwt)) + 
  geom_point(alpha = .5) +
  geom_line(aes(y = pred), color = "red") + 
  facet_grid(~model)
```


